services:
  db:
    image: postgres:16
    container_name: hackathon_db
    environment:
      - POSTGRES_DB=HackathonHSE-25
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=paralledp
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - kopimelik
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: hackathon_backend
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=HackathonHSE-25
      - DB_USER=postgres
      - DB_PASSWORD=paralledp
      - ASPNETCORE_URLS=http://+:8080
    networks:
      - kopimelik
    expose:
      - "8080"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: hackathon_frontend
    depends_on:
      - backend
    networks:
      - kopimelik
    expose:
      - "80"

  nginx:
    image: nginx:alpine
    container_name: hackathon_nginx
    ports:
      - "10880:10880"
      - "10830:10830"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend
    networks:
      - kopimelik

networks:
  kopimelik:
    driver: bridge

volumes:
  postgres_data:
