services:
  db:
    image: postgres:16
    container_name: hackathon_db
    environment:
      - POSTGRES_DB=HackathonHSE-25
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=paralledp
    volumes: # Без тома данные будут теряться
      - postgres_data:/var/lib/postgresql/data
    networks: # Подключение к сети
      - kopimelik
    ports:
      - "5433:5432" # 5433 на хосте, а 5432 внутри контейнера
    healthcheck: # Проверка состояния БД
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: hackathon_backend
    environment:
      - DB_HOST=db
      - DB_PORT=5432 # Порт внутри контейнера, всегда 5432
      - DB_NAME=HackathonHSE-25
      - DB_USER=postgres
      - DB_PASSWORD=paralledp
      - ASPNETCORE_URLS=http://+:8080 # На нем ASP.NET слушает запросы
    networks:
      - kopimelik
    ports:
      - "8080:8080" # Проброс одинаковый и внутри и на хосте
    depends_on: # Проверка БД
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: hackathon_frontend
    depends_on: # backend должен запуститься раньше
      - backend
    networks:
      - kopimelik
    ports:
      - "3000:80" # В контейнере слушает на 80, а отправляет на 3000 - обращаться к http://localhost:3000

networks:
  kopimelik: # Сеть
    driver: bridge # Дефолтная сеть

volumes:
  postgres_data: # Docker автоматически создаст и будет управлять этим томом, нужно для того, чтобы данные не стирались при перезапуске
